companies:
  - Greenvolt
  - Capwatt
  - Ecoinside
  - DST Solar
  - Martifer
  - Mota-Engil Renewing
  - Efacec
  - CME
  - Galp
  - EDP Renováveis
  - Helexia
  - Voltalia Portugal
  - Endesa Portugal
  - Iberdrola Portugal
buyers_investors:
  - EDP
  - Galp
  - Iberdrola
  - Endesa
  - Engie
  - TotalEnergies
  - Brookfield
  - Macquarie
  - Ardian
  - Antin
  - EQT
  - Marguerite
  - Mirova
  - Meridiam
  - Cubico
